CREATE DATABASE productdb IF NOT EXISTS;

USE productdb;

CREATE TABLE product(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(400) NOT NULL,
    price DECIMAL,
    createAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

 